name:                trade-sim
version:             0.1.0.0
github:              "githubuser/trade-sim"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/trade-sim#readme>

dependencies:
- base >= 4.7 && < 5
- fgl
- containers
- aeson
- bytestring
- tasty
- tasty-hunit


default-extensions:
- OverloadedStrings
- DeriveGeneric
- NamedFieldPuns
- GeneralizedNewtypeDeriving

library:
  source-dirs: src

executables:
  trade-sim-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trade-sim

tests:
  trade-sim-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trade-sim
